package bo;
// Generated 2014-nov-12 11:07:51 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TPost generated by hbm2java
 */
public class Post  implements java.io.Serializable {


     private Integer id;
     private Integer user;
     private Date date;
     private String message;

    public Post() {
    }

	
    public Post(Integer user, Date date) {
        this.user = user;
        this.date = date;
    }
    public Post(Integer user, Date date, String message) {
       this.user = user;
       this.date = date;
       this.message = message;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getUser() {
        return this.user;
    }
    
    public void setUser(Integer user) {
        this.user = user;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }




}


