package bo;
// Generated 2014-nov-12 11:07:51 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TMessage generated by hbm2java
 */
public class TMessage  implements java.io.Serializable {


     private Integer id;
     private int sender;
     private int receiver;
     private Date date;
     private String message;

    public TMessage() {
    }

	
    public TMessage(int sender, int receiver, Date date) {
        this.sender = sender;
        this.receiver = receiver;
        this.date = date;
    }
    public TMessage(int sender, int receiver, Date date, String message) {
       this.sender = sender;
       this.receiver = receiver;
       this.date = date;
       this.message = message;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getSender() {
        return this.sender;
    }
    
    public void setSender(int sender) {
        this.sender = sender;
    }
    public int getReceiver() {
        return this.receiver;
    }
    
    public void setReceiver(int receiver) {
        this.receiver = receiver;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }




}


