package bo;
// Generated 2014-nov-12 11:07:51 by Hibernate Tools 4.3.1



/**
 * TUser generated by hbm2java
 */
public class User implements java.io.Serializable {


     private Integer id;
     private String username;
     private String password;

    public User() {
    }

    public User(String username, String password) {
       this.username = username;
       this.password = password;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    
    @Override
    public boolean equals(Object other){
        User user=(User)other;
        
        return user.getId()==id;
    }




}


